apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks
  labels:
    app: eks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks
  template:
    metadata:
      labels:
        app: eks
    spec:
      containers:
        - name: eks
          image: 941824419453.dkr.ecr.us-east-1.amazonaws.com/eks:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
