name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | \
        docker login --username AWS --password-stdin 941824419453.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build, tag and push image to ECR
      run: |
        IMAGE_URI=941824419453.dkr.ecr.ap-south-1.amazonaws.com/demo-app:latest
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name demo-cluster --region ap-south-1

    - name: Replace image URI in deployment.yaml
      run: sed -i "s|<ECR_URI>|941824419453.dkr.ecr.ap-south-1.amazonaws.com/demo-app:latest|g" k8s/deployment.yaml

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
